export type Role = "SA" | "A";
export type BadgeType = "alert" | "live" | "info" | "rd";

export interface SubMenuItem {
    label: string;
    path: string;
    role: Role;
}

export interface MenuItem {
    id: string;
    icon: string;
    label: string;
    path: string;
    role: Role;
    badge: string | null;
    badgeType?: BadgeType;
    color: string;
    sub: SubMenuItem[];
}

export const MENU_CONFIG: MenuItem[] = [
    {
        id: "dashboard",
        icon: "⊞",
        label: "Dashboard",
        path: "/admin",
        role: "SA",
        badge: null,
        color: "#38bdf8",
        sub: [
            { label: "Overview & KPIs", path: "/admin/overview", role: "SA" },
            { label: "Live Online Users", path: "/admin/live-users", role: "SA" },
            { label: "Platform Health", path: "/admin/health", role: "SA" },
            { label: "API Status Monitor", path: "/admin/api-status", role: "SA" },
            { label: "Quick Actions", path: "/admin/quick-actions", role: "SA" },
        ],
    },
    {
        id: "auth",
        icon: "⊡",
        label: "Auth & Security",
        path: "/admin/auth",
        role: "SA",
        badge: null,
        color: "#a78bfa",
        sub: [
            { label: "Admin Accounts", path: "/admin/admins", role: "SA" },
            { label: "Create Admin", path: "/admin/admins/create", role: "SA" },
            { label: "Role & Permissions", path: "/admin/roles", role: "SA" },
            { label: "Active Sessions", path: "/admin/sessions", role: "SA" },
            { label: "Login Audit Log", path: "/admin/audit/login", role: "SA" },
            { label: "Security Events", path: "/admin/audit/security", role: "SA" },
            { label: "Banned IP Addresses", path: "/admin/security/ips", role: "SA" },
            { label: "Two-Factor Auth", path: "/admin/security/2fa", role: "SA" },
        ],
    },
    {
        id: "users",
        icon: "⊙",
        label: "User Management",
        path: "/admin/users",
        role: "A",
        badge: null,
        color: "#34d399",
        sub: [
            { label: "All Users", path: "/admin/users", role: "A" },
            { label: "Search & Filter", path: "/admin/users/search", role: "A" },
            { label: "User Profile View", path: "/admin/users/:id", role: "A" },
            { label: "Edit User Profile", path: "/admin/users/:id/edit", role: "A" },
            { label: "User Activity Timeline", path: "/admin/users/:id/activity", role: "A" },
            { label: "Verified Accounts", path: "/admin/users/verified", role: "A" },
            { label: "Suspended Users", path: "/admin/users/suspended", role: "A" },
            { label: "Banned Users", path: "/admin/users/banned", role: "SA" },
            { label: "Warn User", path: "/admin/users/warn", role: "A" },
            { label: "Suspend User", path: "/admin/users/suspend", role: "A" },
            { label: "Ban User", path: "/admin/users/ban", role: "SA" },
            { label: "Restore Account", path: "/admin/users/restore", role: "A" },
            { label: "User Badges & Roles", path: "/admin/users/badges", role: "SA" },
            { label: "Online / Offline Status", path: "/admin/users/status", role: "A" },
        ],
    },
    {
        id: "moderation",
        icon: "⊘",
        label: "Content Moderation",
        path: "/admin/moderation",
        role: "A",
        badge: "38",
        badgeType: "alert",
        color: "#f87171",
        sub: [
            { label: "Report Queue", path: "/admin/reports", role: "A" },
            { label: "Pending Reports", path: "/admin/reports/pending", role: "A" },
            { label: "Resolved Reports", path: "/admin/reports/resolved", role: "A" },
            { label: "Dismissed Reports", path: "/admin/reports/dismissed", role: "A" },
            { label: "Post Moderation", path: "/admin/moderation/posts", role: "A" },
            { label: "Comment Moderation", path: "/admin/moderation/comments", role: "A" },
            { label: "Message Moderation", path: "/admin/moderation/messages", role: "A" },
            { label: "Spam Detection", path: "/admin/moderation/spam", role: "A" },
            { label: "Harassment Flags", path: "/admin/moderation/harassment", role: "A" },
            { label: "Moderation History", path: "/admin/moderation/history", role: "A" },
            { label: "AI Toxic Content Flags", path: "/admin/moderation/ai", role: "SA" },
        ],
    },
    {
        id: "chat",
        icon: "◫",
        label: "Chat & Messaging",
        path: "/admin/chat",
        role: "A",
        badge: null,
        color: "#38bdf8",
        sub: [
            { label: "Conversation Monitor", path: "/admin/chat/monitor", role: "A" },
            { label: "Flagged Messages", path: "/admin/chat/flagged", role: "A" },
            { label: "Group Chats", path: "/admin/chat/groups", role: "A" },
            { label: "Media Uploads", path: "/admin/chat/media", role: "A" },
            { label: "Message Statistics", path: "/admin/chat/stats", role: "SA" },
            { label: "Deleted Message Log", path: "/admin/chat/deleted", role: "SA" },
        ],
    },
    {
        id: "calls",
        icon: "◎",
        label: "Calls & Video",
        path: "/admin/calls",
        role: "A",
        badge: null,
        color: "#facc15",
        sub: [
            { label: "Active Calls (Live)", path: "/admin/calls/active", role: "A" },
            { label: "Audio Call History", path: "/admin/calls/audio", role: "A" },
            { label: "Video Call History", path: "/admin/calls/video", role: "A" },
            { label: "Missed Calls", path: "/admin/calls/missed", role: "A" },
            { label: "Call Duration Stats", path: "/admin/calls/duration", role: "SA" },
            { label: "Call Analytics", path: "/admin/calls/analytics", role: "SA" },
            { label: "TURN Server Status", path: "/admin/calls/turn", role: "SA" },
            { label: "WebRTC Signal Logs", path: "/admin/calls/webrtc", role: "SA" },
        ],
    },
    {
        id: "rooms",
        icon: "◑",
        label: "Voice Rooms",
        path: "/admin/rooms",
        role: "A",
        badge: "Live",
        badgeType: "live",
        color: "#fb923c",
        sub: [
            { label: "Active Rooms (Live)", path: "/admin/rooms/active", role: "A" },
            { label: "All Rooms History", path: "/admin/rooms/history", role: "A" },
            { label: "Monitor Room (Silent)", path: "/admin/rooms/monitor", role: "A" },
            { label: "Force Close Room", path: "/admin/rooms/close", role: "A" },
            { label: "Remove Host", path: "/admin/rooms/remove-host", role: "A" },
            { label: "Karaoke Sessions", path: "/admin/rooms/karaoke", role: "A" },
            { label: "Room Reports", path: "/admin/rooms/reports", role: "A" },
            { label: "Speaker Stats", path: "/admin/rooms/speakers", role: "SA" },
            { label: "Audience Analytics", path: "/admin/rooms/analytics", role: "SA" },
        ],
    },
    {
        id: "feed",
        icon: "◐",
        label: "Social Feed",
        path: "/admin/feed",
        role: "A",
        badge: null,
        color: "#4ade80",
        sub: [
            { label: "All Posts", path: "/admin/feed/posts", role: "A" },
            { label: "Trending Posts", path: "/admin/feed/trending", role: "A" },
            { label: "Country Topics", path: "/admin/feed/country", role: "A" },
            { label: "Reported Posts", path: "/admin/feed/reported", role: "A" },
            { label: "Removed Posts", path: "/admin/feed/removed", role: "A" },
            { label: "Trending Hashtags", path: "/admin/feed/hashtags", role: "SA" },
            { label: "Feed Algorithm Config", path: "/admin/feed/algorithm", role: "SA" },
            { label: "Post Analytics", path: "/admin/feed/analytics", role: "SA" },
            { label: "Saved Posts Overview", path: "/admin/feed/saved", role: "SA" },
        ],
    },
    {
        id: "gifts",
        icon: "◇",
        label: "Gifts & Economy",
        path: "/admin/gifts",
        role: "SA",
        badge: null,
        color: "#f472b6",
        sub: [
            { label: "Gift Catalog", path: "/admin/gifts", role: "SA" },
            { label: "Add New Gift", path: "/admin/gifts/create", role: "SA" },
            { label: "Edit / Manage Gifts", path: "/admin/gifts/manage", role: "SA" },
            { label: "Gift Categories", path: "/admin/gifts/categories", role: "SA" },
            { label: "Gift Transactions (Live)", path: "/admin/gifts/transactions", role: "SA" },
            { label: "Gift Leaderboard", path: "/admin/gifts/leaderboard", role: "SA" },
            { label: "Top Senders", path: "/admin/gifts/top-senders", role: "SA" },
            { label: "Top Earners (Influencers)", path: "/admin/gifts/top-earners", role: "SA" },
            { label: "Coin Purchase History", path: "/admin/coins/purchases", role: "SA" },
            { label: "Coin Balances Overview", path: "/admin/coins/balances", role: "SA" },
            { label: "Revenue from Coins", path: "/admin/coins/revenue", role: "SA" },
            { label: "Transaction Ledger", path: "/admin/economy/ledger", role: "SA" },
            { label: "Economic Balance Ratio", path: "/admin/economy/balance", role: "SA" },
            { label: "Payment Gateway Logs", path: "/admin/economy/payments", role: "SA" },
            { label: "Refund Requests", path: "/admin/economy/refunds", role: "SA" },
        ],
    },
    {
        id: "translation",
        icon: "⊕",
        label: "Translation System",
        path: "/admin/translation",
        role: "SA",
        badge: "180+",
        badgeType: "info",
        color: "#38bdf8",
        sub: [
            { label: "Language Management", path: "/admin/languages", role: "SA" },
            { label: "Add Language", path: "/admin/languages/create", role: "SA" },
            { label: "Translation API Usage", path: "/admin/translation/usage", role: "SA" },
            { label: "Translation Cache", path: "/admin/translation/cache", role: "SA" },
            { label: "Error Rate Monitor", path: "/admin/translation/errors", role: "SA" },
            { label: "Auto-Translate Config", path: "/admin/translation/config", role: "SA" },
            { label: "Language Usage Stats", path: "/admin/translation/stats", role: "SA" },
            { label: "Language Heatmap", path: "/admin/translation/heatmap", role: "SA" },
        ],
    },
    {
        id: "matching",
        icon: "◌",
        label: "Partner Matching",
        path: "/admin/matching",
        role: "SA",
        badge: null,
        color: "#c084fc",
        sub: [
            { label: "Match Overview", path: "/admin/matching/overview", role: "SA" },
            { label: "Match Success Rate", path: "/admin/matching/success", role: "SA" },
            { label: "Algorithm Config", path: "/admin/matching/config", role: "SA" },
            { label: "Scoring Weights", path: "/admin/matching/weights", role: "SA" },
            { label: "Match History", path: "/admin/matching/history", role: "SA" },
            { label: "Pending Matches", path: "/admin/matching/pending", role: "SA" },
            { label: "Run Matching Job", path: "/admin/matching/run", role: "SA" },
            { label: "Rejected Matches", path: "/admin/matching/rejected", role: "SA" },
        ],
    },
    {
        id: "notifications",
        icon: "◯",
        label: "Notifications",
        path: "/admin/notifications",
        role: "SA",
        badge: null,
        color: "#fb923c",
        sub: [
            { label: "Send Announcement", path: "/admin/notifications/broadcast", role: "SA" },
            { label: "Push Log (FCM)", path: "/admin/notifications/push-log", role: "SA" },
            { label: "Delivery Reports", path: "/admin/notifications/delivery", role: "SA" },
            { label: "Failed Notifications", path: "/admin/notifications/failed", role: "SA" },
            { label: "Device Tokens (FCM)", path: "/admin/notifications/devices", role: "SA" },
            { label: "Notification Templates", path: "/admin/notifications/templates", role: "SA" },
            { label: "Quiet Hours Config", path: "/admin/notifications/quiet", role: "SA" },
        ],
    },
    {
        id: "analytics",
        icon: "⊟",
        label: "Analytics",
        path: "/admin/analytics",
        role: "SA",
        badge: null,
        color: "#34d399",
        sub: [
            { label: "Platform Overview", path: "/admin/analytics/overview", role: "SA" },
            { label: "User Growth (DAU/MAU)", path: "/admin/analytics/users", role: "SA" },
            { label: "Retention & Churn", path: "/admin/analytics/retention", role: "SA" },
            { label: "Country Distribution", path: "/admin/analytics/countries", role: "SA" },
            { label: "Language Heatmap", path: "/admin/analytics/languages", role: "SA" },
            { label: "Cultural Exchange Map", path: "/admin/analytics/culture-map", role: "SA" },
            { label: "Trending Topics", path: "/admin/analytics/trending", role: "SA" },
            { label: "Call Analytics", path: "/admin/analytics/calls", role: "SA" },
            { label: "Feed Engagement", path: "/admin/analytics/feed", role: "SA" },
            { label: "Revenue Analytics", path: "/admin/analytics/revenue", role: "SA" },
            { label: "API Response Times", path: "/admin/analytics/api", role: "SA" },
            { label: "Error Rates (Sentry)", path: "/admin/analytics/errors", role: "SA" },
            { label: "Queue Performance", path: "/admin/analytics/queues", role: "SA" },
        ],
    },
    {
        id: "sl",
        icon: "⊗",
        label: "Speech Learning (SL)",
        path: "/admin/sl",
        role: "SA",
        badge: "R&D",
        badgeType: "rd",
        color: "#facc15",
        sub: [
            { label: "SL Overview", path: "/admin/sl/overview", role: "SA" },
            { label: "Grammar Lessons", path: "/admin/sl/grammar", role: "SA" },
            { label: "Vocabulary Lists", path: "/admin/sl/vocabulary", role: "SA" },
            { label: "Pronunciation Scoring", path: "/admin/sl/pronunciation", role: "SA" },
            { label: "Tongue Twister Module", path: "/admin/sl/twisters", role: "SA" },
            { label: "Daily Challenges", path: "/admin/sl/challenges", role: "SA" },
            { label: "User SL Progress", path: "/admin/sl/progress", role: "SA" },
            { label: "SL Analytics", path: "/admin/sl/analytics", role: "SA" },
            { label: "Flutter Integration", path: "/admin/sl/flutter", role: "SA" },
        ],
    },
    {
        id: "settings",
        icon: "⊞",
        label: "Platform Settings",
        path: "/admin/settings",
        role: "SA",
        badge: null,
        color: "#94a3b8",
        sub: [
            { label: "General Settings", path: "/admin/settings/general", role: "SA" },
            { label: "Feature Flags", path: "/admin/settings/features", role: "SA" },
            { label: "Maintenance Mode", path: "/admin/settings/maintenance", role: "SA" },
            { label: "Rate Limit Config", path: "/admin/settings/rate-limits", role: "SA" },
            { label: "TURN Server Config", path: "/admin/settings/turn", role: "SA" },
            { label: "Storage Config (S3)", path: "/admin/settings/storage", role: "SA" },
            { label: "Translation API Keys", path: "/admin/settings/translation", role: "SA" },
            { label: "Firebase / FCM Config", path: "/admin/settings/firebase", role: "SA" },
            { label: "Payment Gateway (Stripe)", path: "/admin/settings/payments", role: "SA" },
            { label: "Email / SMTP Config", path: "/admin/settings/email", role: "SA" },
            { label: "WebSocket Config", path: "/admin/settings/websocket", role: "SA" },
            { label: "CDN / CloudFront", path: "/admin/settings/cdn", role: "SA" },
        ],
    },
    {
        id: "audit",
        icon: "⊠",
        label: "Audit Logs",
        path: "/admin/audit",
        role: "SA",
        badge: null,
        color: "#64748b",
        sub: [
            { label: "Admin Action Log", path: "/admin/audit/actions", role: "SA" },
            { label: "User Ban / Suspend Log", path: "/admin/audit/moderation", role: "SA" },
            { label: "API Request Log", path: "/admin/audit/api", role: "SA" },
            { label: "Error Log", path: "/admin/audit/errors", role: "SA" },
            { label: "Queue Monitor (Horizon)", path: "/admin/audit/horizon", role: "SA" },
            { label: "System Event Log", path: "/admin/audit/system", role: "SA" },
        ],
    },
];

export const BADGE_STYLES: Record<BadgeType, { bg: string, color: string, border: string }> = {
    alert: { bg: "rgba(248,113,113,0.15)", color: "#f87171", border: "rgba(248,113,113,0.3)" },
    live: { bg: "rgba(52,211,153,0.15)", color: "#34d399", border: "rgba(52,211,153,0.3)" },
    info: { bg: "rgba(56,189,248,0.15)", color: "#38bdf8", border: "rgba(56,189,248,0.3)" },
    rd: { bg: "rgba(250,204,21,0.15)", color: "#facc15", border: "rgba(250,204,21,0.3)" },
};

export const ROLE_STYLE: Record<Role, { bg: string, color: string, border: string }> = {
    SA: { bg: "rgba(167,139,250,0.12)", color: "#a78bfa", border: "rgba(167,139,250,0.25)" },
    A: { bg: "rgba(52,211,153,0.10)", color: "#34d399", border: "rgba(52,211,153,0.22)" },
};
